// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Liftr.Migrations
{
    [DbContext(typeof(LiftrContext))]
    [Migration("20231113051945_SeedExercises")]
    partial class SeedExercises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-rc.2.23480.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Liftr.Data.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("056f80ec-226d-4e45-a071-47f4bf2838a6"),
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = new Guid("6747faba-5f84-44d2-88fa-9a7670ea69c3"),
                            Name = "Squat"
                        },
                        new
                        {
                            Id = new Guid("57aeb0af-1178-454f-a941-4a826cf8039b"),
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = new Guid("700190a7-a117-477a-8bf5-655bfa263dc7"),
                            Name = "Overhead Press"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
